docs: proposed ADR for LTI feature control
openedx/xblock-lti-consumer pull request #287
Opened 2022-09-19 17:41 UTC by ashultz0

Depends on 0007-lti-1p3-decoupling.rst which is currently in PR.

Mostly of interest to @Zacharis278 @MichaelRoytman and @giovannicimolin as this extends the things we've been talking about. Short version is let's not add fancy and confusing configuration, let's plan to split out the xblock and LMS items after we get a clear idea of usage.

2022-10-11 13:37 UTC, ashultz0 commented
@Zacharis278 and @giovannicimolin please have a look, I think this is not too controversial which may be why no comments :)

2022-10-13 17:34 UTC, schenedx requested changes
Provided my feedback inline.

2022-10-13 17:34 UTC, schenedx commented on docs/decisions/0008-lti-feature-separation.rst
> +What if anything should we do to prevent LTI from being configured in impossible ways?
#NIT this sentence is hard to understand for me. Could you please simplify, or make it more direct?

2022-10-13 17:34 UTC, schenedx commented on docs/decisions/0008-lti-feature-separation.rst
> +Once we have separated LTI launch and used it in an IDA we will have a better idea of how it works in practice. At that point we will split the generic LTI parts into their own library which will be
"We expect `that`"

2022-10-13 17:34 UTC, schenedx commented on docs/decisions/0008-lti-feature-separation.rst
> +* First, finish the work described in earlier ADRs to separate launch from xblock.
I feel the real consequences are, some users of the library other than 2U Cosmonauts team will be confused about the current state.
Going further, some user of this library might make API calls into this library that might make future separation difficult. Maybe we are OK with that?

2022-10-14 14:31 UTC, ashultz0 commented
I think Simon is right and the reason this ADR is a little weird is that some of it is well covered in ADR 00001 and the rest is a "let's not do this right now". Closing this out. :)

2022-10-14 14:31 UTC, closed without merging